import type { NextPage } from "next";
import Head from "next/head";
import About from "../sections/About";
import Header from "../sections/Header";
import SelectedProjects from "../sections/SelectedProjects";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative overflow-y-scroll snap-mandatory snap-y h-screen [&>section]:p-10 [&>section]:snap-start">
        <Header />
        <About />
        <SelectedProjects />
      </main>
    </div>
  );
};

export default Home;
